grpc:
  GLOBAL:
    negotiation-type: PLAINTEXT
    max-inbound-message-size: 8MB
  client:
    verification:
      address: static://localhost:9090

spring:
  liquibase:
    change-log: classpath:/db/changelog/db-changelog.xml
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"